name: coleccion_numismatica
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # Iconos
  cupertino_icons: ^1.0.8
  # Almacenamiento local
  hive_flutter: ^1.1.0 
  path_provider: ^2.1.5
  path: ^1.9.0
  # Manejo de imágenes
  image_picker: ^1.1.2
  image: ^4.3.0  
  image_cropper: ^8.0.0
  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.5.0
  #firebase_storage: ^12.3.3
  # Autenticación y permisos
  google_sign_in: ^6.1.0
  permission_handler: ^11.3.1
  # Estadisticas
  fl_chart: ^0.70.0
  # Iconos
  font_awesome_flutter: ^10.7.0
  #PDF
  pdf: ^3.11.0
  printing: ^5.13.0
  # Compartición de archivos
  share_plus: ^10.1.0
  file_picker: ^8.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

